-- Your SQL goes here

CREATE TABLE class (
    id  INTEGER PRIMARY KEY AUTO_INCREMENT,
    teacher TEXT NOT NULL
);


CREATE TABLE grades (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    grade INTEGER NOT NULL
);

CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTO_INCREMENT,
    class_id INTEGER NOT NULL,
    grades_id INTEGER NOT NULL,
    name TEXT NOT NULL
);

